[theme]
# The configuration here applies some Civis-specific colors and styling.
# For info on how to apply your own theme, see
# https://docs.streamlit.io/develop/concepts/configuration/theming-customize-colors-and-borders.
primaryColor = "#215470"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#215470"
font = "Lato,sans serif"
base = "light"
baseRadius="4px"
blueColor = "#4485B6"
redColor = "#D33D3D"
orangeColor = "#DD5C21"
yellowColor = "#F1A137"
greenColor = "#14B8A6"
